### ISSUE TITLE
Provide support for SBT when using Scala instead of Gradle

### ISSUE THREAD

**Issue by slevine** [jorgebastida/gordon#15]
SBT is the standard build tool for Scala projects, but understand why Gradle is used here.  

As an additional option, it would be great to be able to use a different build tool.

**Comment by jorgebastida** [comment]
I am quite illiterate in terms of Java/JVM building tools I'm afraid sorry! I pick ``gradle`` because AWS suggested it in the documentation and looked neat.

The good news is that you can use any build tool you want!  You can use as reference the ``Golang`` example. https://github.com/jorgebastida/gordon/blob/master/examples/go/goexample/settings.yml#L7-L10

When you define a ``build``section in your lambda, you override the "default" build process of the runtime, and you can use any tool you want! The only requirement for gordon to be happy is that you leave "what you want to zip within the lambda" in the ``{ target }`` directory. That's all.

For more information: http://gordon.readthedocs.io/en/latest/lambdas.html#build

**Comment by stevelevine** [comment]
@jorgebastida - Makes sense, will give it a try, thanks!

**Comment by slevine** [comment]
@jorgebastida - Makes sense, will give it a try.  Thanks.
