### ISSUE TITLE
How to reuse AWS policy or role between lambdas and/or projects?

### ISSUE THREAD

**Issue by zlatkoc** [jorgebastida/gordon#21]
Hi,

What would be best way to reuse AWS policies or roles between lambdas and / or projects?

Currently we have two options:

- define policy inline under policies for each lambda
- override role for each lambda

None of the two is optimal:

- the first does not support reuse
- in second we need to include policies generated by gordon (documentation does not state which)
- also using parameter like ref://RoleArn is currently not supported (gordon throws exception)

I am looking for a solution to have a custom role attached to lambdas or to whole project.

Hmm, maybe I need just to prepare PR ;-)

**Comment by jorgebastida** [comment]
Hello @zlatkoc the best thing would be to specify a custom role to your lambdas using ``role`` and point that to the arn of your role. That functionality should be in place... but if you have tested it and it raises an exception... might be the case I've break it recently. 

doc: http://gordon.readthedocs.io/en/latest/lambdas.html#role
relevant code: https://github.com/jorgebastida/gordon/blob/master/gordon/resources/lambdas.py#L155-L186

If that code works / we make it work, you should be able to do do in your lambdas something like ``role: ref://RoleArn`` and then set the value of ``RoleArn`` using parameters (http://gordon.readthedocs.io/en/latest/parameters.html)

Remember that you can create a ``common.yml`` file in your ``parameters`` folder in order to make the value of ``RoleArn`` the same accross stages (if that's something you want to do).

In terms of "what to put" in that role. By default gordon adds (if ``auto-vpc-policy`` is True) the following policy https://github.com/jorgebastida/gordon/blob/master/gordon/resources/lambdas.py#L99-L119

Hope this helps you. Let me know if the ``role`` parameter has finally a bug, and I'll try to fix it - Feel free to send a PR if you manage to make it work before I can jump into this.

**Comment by jorgebastida** [comment]
Hello @zlatkoc - I've tested this, and it was the case that ``role`` could be the ``arn`` of an AWS role.... the problem was that it couldn't be a reference to a parameter.

I've just pushed some changes that would make that possible (https://github.com/jorgebastida/gordon/commit/cd4bbd34565a3440aeafdaafb3585ea03c3debb4#diff-05897d01464466be4c67e76bf9940607R166) from ``0.2.1`` onwards.

Let me know if this makes your use case possible.
