### ISSUE TITLE
Add Windows Support to Gordon

### ISSUE THREAD

**Issue by petemounce** [jorgebastida/gordon#47]
I've had a go with gordon since it looks like exactly what I've been looking for - something to shove lambdas into the cloud and allow me to wire them together (crucially, contract first with swagger).

I'm having a problem when I build:

```
> gordon build
Loading project resources
Loading installed applications
  contrib_lambdas:
    Ô£ô lambdas:version
  firstapp:
    Ô£ô lambdas:helloworld
Building project...
  0001_p.json

Error building lambda 'version'!
cmd: cd C:\Users\peter.mounce\.gordon\tmp6oo2vu && find . -name "*.pyc" -delete

Access denied - .

File not found - -NAME

File not found - -DELETE
```

I'm using Windows 8.1, python 2.7.10, gordon 0.2.1 (I think - I pip installed it moments ago).

I've done, in a fresh directory

``` shell
gordon start project demo
cd demo
gordon startapp firstapp --runtime=js
gordon build # and got the output above
# edited /settings.yml to uncomment the firstapp array element inside the apps array
gordon build # and got the output above again
```

I'd expected to see the output in the quickstart.

The directory mentioned in the output does not exist.

I've tried both an admin powershell prompt and a regular one. Then a cmd for good measure; no differences.

**Comment by jorgebastida** [comment]
Hello @petemounce I'm afraid the chances of gordon working on windows are nearly zero at the moment :(

That been said, making it work should not be "that" hard as far as a windows user can translate few commands gordon runs in the shell to the "windows world".

From the top of my head the things which are broken for sure are:
* ``resources/lambdas/PythonLambda._get_default_build_command``
* ``resources/lambdas/PythonLambda._get_default_run_command``
* ``resources/lambdas/NodeLambda._get_default_build_command``

In order to fix those, I think the easiest thing to do would be to make the Project aware of the platform with some ``platform`` property which either return ``windows`` or ``linux`` and then, make the above commands return the "windows version" of what they are doing.

Apart from that... there might be not that many more broken things.

**Comment by jonapich** [comment]
FWIW, it works using windows 10's bash support...

**Comment by jorgebastida** [comment]
Good to know @jonapich Thanks!
